 /* -- Base de datos ya creada en script anterior.
DROP DATABASE IF EXISTS `bernutss_db`;
CREATE DATABASE `bernutss_db`;
USE `bernutss_db`; */


-- Crear la tabla LOG_AUDITORIA
DROP TABLE IF EXISTS bernutss_db.LOG_AUDITORIA;
CREATE TABLE IF NOT EXISTS bernutss_db.LOG_AUDITORIA 
(
    ID_LOG INT AUTO_INCREMENT,
    NOMBRE_DE_ACCION VARCHAR(10),
    NOMBRE_TABLA VARCHAR(50),
    USUARIO VARCHAR(100),
    FECHA_UPD_INS_DEL DATE,
    PRIMARY KEY (ID_LOG)
);

/* LA TABLA USUARIO YA FUE CREADA EN SCRIPT DE TABLAS
  CREATE TABLE IF NOT EXISTS  usuarios (
   `id` INT AUTO_INCREMENT COMMENT 'CLAVE PRIMARIA' ,
   `nombre` VARCHAR(150) NOT NULL COMMENT 'NOMBRE DEL USUARIO',
   `apellido` VARCHAR(150) NOT NULL COMMENT 'APELLIDO DEL USUARIO',
   `mail` VARCHAR(150) NOT NULL COMMENT 'CORREO ELECTRONICO DEL USUARIO ',
   `contrasenia` VARCHAR(150) NOT NULL COMMENT 'CONTRASEÑA DEL USUARIO',
   `imagen` BLOB COMMENT 'IMAGEN DE PERFIL',
   PRIMARY KEY (`id`)
);*/

-- Crear el trigger TRG_LOG_tipo_usuario
DROP TRIGGER IF EXISTS TRG_LOG_usuarios;
DELIMITER //
CREATE TRIGGER TRG_LOG_usuarios AFTER INSERT ON bernutss_db.usuarios
FOR EACH ROW 
BEGIN
    INSERT INTO bernutss_db.LOG_AUDITORIA (NOMBRE_DE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_UPD_INS_DEL)
    VALUES ('INSERT', 'usuarios', CURRENT_USER(), NOW());
END//
DELIMITER ;

-- Crear la tabla LOG_AUDITORIA_2
DROP TABLE IF EXISTS bernutss_db.LOG_AUDITORIA_2;
CREATE TABLE IF NOT EXISTS bernutss_db.LOG_AUDITORIA_2 
(
    ID_LOG INT AUTO_INCREMENT,
    PROVINCIA VARCHAR(50) DEFAULT NULL,
    ID_PROVINCIA INT NOT NULL,
    NOMBRE_DE_ACCION VARCHAR(10),
    NOMBRE_TABLA VARCHAR(50),
    USUARIO VARCHAR(100),
    FECHA_UPD_INS_DEL DATE,
    PRIMARY KEY (ID_LOG)
);

-- Crear el trigger TRG_LOG_tipo_usuario_2
DROP TRIGGER IF EXISTS TRG_LOG_tipo_usuario_2;
DELIMITER //
CREATE TRIGGER TRG_LOG_usuarios_2 AFTER INSERT ON bernutss_db.usuarios
FOR EACH ROW 
BEGIN
    INSERT INTO bernutss_db.LOG_AUDITORIA_2 (PROVINCIA, ID_PROVINCIA, NOMBRE_DE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_UPD_INS_DEL)
    VALUES (NULL, NEW.id, 'INSERT', 'usuarios', CURRENT_USER(), NOW());
END//
DELIMITER ;

-- Mostrar el contenido de las tablas LOG_AUDITORIA y LOG_AUDITORIA_2
SELECT * FROM bernutss_db.LOG_AUDITORIA;
SELECT * FROM bernutss_db.LOG_AUDITORIA_2;

INSERT INTO usuarios (nombre, apellido, mail, contrasenia)
VALUES ("Leandro", "Gonzalez","leandro@hotmail.com", "****") ;


select * from tipo_usuarios;


